Created structure of project
lionslon/yap-gophermart pull request #1
Opened 2024-08-05 15:53 UTC by lionslon

2024-11-07 22:46 UTC, avhitrov requested changes
В общем и целом все спроектировано грамотно, но есть ряд ошибок и неряшливостей, отмечены комментариями в коде. В частности, требует доработки процедура мягкого шатдауна.

2024-11-07 22:46 UTC, avhitrov commented on internal/db/order.go
> +	}
При переборе строк rows.Next() возвращает bool, в котором false который может быть результатом как нормального достижения конца списка, так и возникшей ошибки. Поэтому после цикла необходимо проверить, не по ошибке ли мы вывалились, и вернуть эту ошибку:
```
if err:= rows.Err(); err != nil {
     return nil, err
}
```

2024-11-07 22:46 UTC, avhitrov commented on internal/db/order.go
> +	}
При переборе строк rows.Next() возвращает bool, в котором false который может быть результатом как нормального достижения конца списка, так и возникшей ошибки. Поэтому после цикла необходимо проверить, не по ошибке ли мы вывалились, и вернуть эту ошибку:
```
if err:= rows.Err(); err != nil {
     return nil, err
}
```

2024-11-07 22:46 UTC, avhitrov commented on internal/db/migrations.go
> +	"github.com/golang-migrate/migrate/v4/source/iofs"
https://t.me/bushigo/27

2024-11-07 22:46 UTC, avhitrov commented on internal/db/balance.go
> +func (db *DB) GetBalance(ctx context.Context, userID string) (*models.UserBalance, error) {
Функция не вносит никаких изменений в БД. Для чего в ней открывать транзакцию? В случае, если возникнет какая-то ошибка, откатываться некуда. Да и SELECT в рамках открытой транзакции будет блокировать записи только в случае, если в него включить суффикс `FOR UPDATE`. Но никакого изменения, повторяю, в рамках данной функции не предусмотрено.

2024-11-07 22:46 UTC, avhitrov commented on internal/db/migrations/00001_init.down.sql
> +DROP TABLE Balances;
Не вижу данной таблицы в init_up

2024-11-07 22:46 UTC, avhitrov commented on internal/server/server.go
> +	go func(ctx context.Context, orders chan<- *models.Order, sleepyChan <-chan int, errs chan<- error) {
Инициализацию и деструктор тикера необходимо перенести сюда, внутрь горутины, так как более нигде он не используется. А здесь удобно будет описать:
```
ticker := time.NewTicker(s.accIntervalTimeout)
defer ticker.Stop()
```

2024-11-07 22:46 UTC, avhitrov commented on internal/server/server.go
> +			}
```suggestion
			if ctx.Err() != nil {
				return
			}
```

2024-11-07 22:46 UTC, avhitrov commented on cmd/gophermart/main.go
> +	}()
Очень плохое решение - отдать закрытие БД на откуп горутине, которая выполнится неизвестно в каком порядке. Она может погасить базу (и скорее всего погасит) ДО того, как будет выключен веб-сервер и ДО того, как отключится горутина, работающая с accrual-системой. Что вызовет панику и потерю данных.

2024-11-07 22:46 UTC, avhitrov commented on internal/server/server.go
> +	go func(ctx context.Context, orders <-chan *models.Order, sleepyChan chan<- int, errs chan<- error) {
В данную горутину следует пробросить wg и после отключения http-сервера дождаться завершения горутины.
```
wg.Add(1)
defer wg.Done()
```

2024-11-07 22:46 UTC, avhitrov commented on cmd/gophermart/main.go
> +		wg.Wait()
db.Close() следует вызывать однозначно после wg.Wait(). В этом случае можно быть уверенным, что все процессы в останавливаемой системе успешно завершились.

2024-11-09 13:46 UTC, lionslon commented on internal/db/order.go
> +	}
Спасибо, добавил!

2024-11-09 13:47 UTC, lionslon commented on internal/db/order.go
> +	}
Спасибо, добавил!

2024-11-09 13:51 UTC, lionslon commented on internal/db/migrations.go
> +	"github.com/golang-migrate/migrate/v4/source/iofs"
Тут разве что пустой строки не хватает, но форматирование кода в 7 спринте даётся.

2024-11-09 13:58 UTC, lionslon commented on internal/db/balance.go
> +func (db *DB) GetBalance(ctx context.Context, userID string) (*models.UserBalance, error) {
Убрал транзакцию

2024-11-09 15:31 UTC, lionslon commented on internal/db/migrations/00001_init.down.sql
> +DROP TABLE Balances;
Поправил

2024-11-09 15:34 UTC, lionslon commented on internal/server/server.go
> +	go func(ctx context.Context, orders chan<- *models.Order, sleepyChan <-chan int, errs chan<- error) {
Перенёс

2024-11-09 15:35 UTC, lionslon commented on internal/server/server.go
> +			}
Принял

2024-11-09 15:51 UTC, lionslon commented on internal/server/server.go
> +	go func(ctx context.Context, orders <-chan *models.Order, sleepyChan chan<- int, errs chan<- error) {
Перенёс

2024-11-09 15:51 UTC, lionslon commented on cmd/gophermart/main.go
> +	}()
Переделал

2024-11-09 15:52 UTC, lionslon commented on cmd/gophermart/main.go
> +		wg.Wait()
Спасибо

2024-11-14 21:43 UTC, avhitrov approved these changes
Все замечания поправлены. Поздравляю с завершением первого дипломного проекта.

2025-01-13 13:00 UTC, merged